window.App.Data = {
    units: {
        "Perl Programs": { icon: "🐪", title: "All Programs" }
    },
    cppFiles: [
        { id: "1_hello_world.pl",            unit: "Perl Programs", title: "1.  Hello World",                      concept: "print Statement",                description: "The simplest Perl program — printing a string to the console using print.", useCase: "Testing environment setup.", bioNote: "Validates that the Perl interpreter is correctly installed." },
        { id: "2_variables.pl",              unit: "Perl Programs", title: "2.  Scalar Variables",                concept: "Scalars ($var)",                 description: "Declaring and printing scalar variables — strings, integers, and floats.", useCase: "Storing single values.", bioNote: "Storing patient IDs, gene names, or individual quality scores." },
        { id: "3_user_input.pl",             unit: "Perl Programs", title: "3.  User Input & Addition",           concept: "STDIN & chomp()",                description: "Reading two numbers from console via STDIN and computing their sum.", useCase: "Interactive scripts.", bioNote: "Accepting custom alignment thresholds from the user at runtime." },
        { id: "4_arrays.pl",                 unit: "Perl Programs", title: "4.  Arrays",                          concept: "Arrays (@array)",                description: "Defining arrays and accessing individual elements with $ and a numeric index.", useCase: "Ordered data storage.", bioNote: "Storing gene identifiers, quality scores, or sequence reads." },
        { id: "5_hashes.pl",                 unit: "Perl Programs", title: "5.  Hashes (Key-Value Pairs)",        concept: "Hashes (%hash)",                 description: "Creating a hash (dictionary) and accessing values by their string keys.", useCase: "Lookup tables.", bioNote: "Mapping codon strings (AUG) to amino acid names (Methionine)." },
        { id: "6_string_concat.pl",          unit: "Perl Programs", title: "6.  String Concatenation",            concept: "Dot (.) Operator",               description: "Using . to join strings, x to repeat, and ++ to increment string characters.", useCase: "Building dynamic strings.", bioNote: "Constructing poly-A tails or repetitive sequence motifs." },
        { id: "7_string_multiply.pl",        unit: "Perl Programs", title: "7.  String Multiply & Increment",     concept: "String Coercion & ++",           description: "Multiplying string-prefixed numbers (Perl uses numeric prefix). Auto-incrementing alphabetic strings.", useCase: "String arithmetic.", bioNote: "Understanding Perl type coercion — critical when processing mixed sequence/quality data." },
        { id: "8_lists.pl",                  unit: "Perl Programs", title: "8.  Lists",                           concept: "List Definition & Slicing",      description: "Defining lists of chars, ints, and strings. Accessing by index, negative index, and slicing multiple elements.", useCase: "Bulk data access.", bioNote: "Extracting subsets of gene positions or codon windows from a sequence array." },
        { id: "9_string_split.pl",           unit: "Perl Programs", title: "9.  Split Function",                  concept: "split()",                        description: "Splitting strings into arrays using space or comma as delimiter.", useCase: "CSV/TSV parsing.", bioNote: "Parsing whitespace-separated BED file fields or comma-delimited FASTA metadata." },
        { id: "10_conditionals.pl",          unit: "Perl Programs", title: "10. Conditionals (if/elsif/unless)",  concept: "if / elsif / unless",            description: "if-elsif chains for multi-branch logic. unless executes when the condition is FALSE.", useCase: "Decision making.", bioNote: "Filtering sequences based on length, GC-content, or quality score thresholds." },
        { id: "11_switch.pl",                unit: "Perl Programs", title: "11. Switch Statement",                concept: "use Switch",                     description: "The Switch module provides case-based branching — matching a variable against values, ranges, arrays, and hashes.", useCase: "Multi-branch dispatch.", bioNote: "Routing sequence analysis tasks based on file type or algorithm selection." },
        { id: "12_loops.pl",                 unit: "Perl Programs", title: "12. Loops (while/for/foreach/until)", concept: "Loop Constructs",                description: "All four Perl loop types: while (condition-first), for (C-style), foreach (iterator), until (runs until true).", useCase: "Iterating collections.", bioNote: "Iterating over every sequence record in a FASTQ file for batch processing." },
        { id: "13_subroutines.pl",           unit: "Perl Programs", title: "13. Subroutines (Average)",           concept: "sub / @_ / scalar(@_)",          description: "Defining a reusable sub that uses @_ for arguments and scalar(@_) for count.", useCase: "Modular code.", bioNote: "Calculating average GC content or quality score across multiple reads." },
        { id: "14_subroutine_input.pl",      unit: "Perl Programs", title: "14. Subroutine with User Input",      concept: "STDIN + split + sub",            description: "Takes space-separated numbers from STDIN, splits into an array, then passes to a subroutine.", useCase: "Interactive subroutines.", bioNote: "User-supplied scoring parameters piped into alignment quality averaging routines." },
        { id: "15_grep_pattern.pl",          unit: "Perl Programs", title: "15. Grep — Pattern Filtering",        concept: "grep() with Regex",              description: "Using grep() to filter arrays: elements ending in a-z, containing digits, starting with a letter.", useCase: "Array filtering.", bioNote: "Extracting gene names matching a specific prefix from large annotation databases." },
        { id: "16_grep_advanced.pl",         unit: "Perl Programs", title: "16. Grep — Advanced Patterns",        concept: "grep() Multiple Patterns",       description: "Applies four different regex patterns to the same array: ending a-z, ending m, starting V, ending k.", useCase: "Multi-filter analysis.", bioNote: "Scanning FASTA headers for sequences from specific organisms or chromosomes." },
        { id: "17_regex_match_sub.pl",       unit: "Perl Programs", title: "17. Match & Substitution",            concept: "=~ m// and s///",                description: "Match operator (=~ m//) returns position data. Substitution operator (s///) replaces first match.", useCase: "Text replacement.", bioNote: "Correcting sequencing errors by replacing invalid nucleotide characters in raw reads." },
        { id: "18_match_operator.pl",        unit: "Perl Programs", title: "18. Match Operator",                  concept: "Prematch, Match, Postmatch",     description: "After a match: the matched text, everything before it, and everything after it can all be captured using special Perl variables.", useCase: "Context extraction.", bioNote: "Isolating a specific motif within a sequence and examining its flanking regions." },
        { id: "19_substitution_operator.pl", unit: "Perl Programs", title: "19. Substitution Operator",           concept: "s/// and /g modifier",           description: "Replaces first match with s///, replaces ALL matches globally with the /g flag.", useCase: "Bulk text replacement.", bioNote: "Normalizing sequence data by replacing all ambiguous bases (X, N) with standard notation." },
        { id: "20_bioinformatics_regex.pl",  unit: "Perl Programs", title: "20. Bioinformatics Regex (Exam)",     concept: "DNA Regex — 3 Exam Questions",   description: "Q1: ATG to TAA regex. Q2: Valid DNA characters only. Q3: ATG with any stop codon (TAA/TAG/TGA). These three regex patterns are the core exam topic.", useCase: "Most important exam topic.", bioNote: "Standard tools for Open Reading Frame (ORF) detection in Perl bioinformatics pipelines." },
        { id: "21_file_handling.pl",         unit: "Perl Programs", title: "21. File Handling (FASTA)",           concept: "open() / while / chomp()",       description: "Opening a file with open(), reading line-by-line in a while loop, stripping newlines with chomp().", useCase: "File I/O.", bioNote: "Parsing FASTA files: detecting header lines vs. sequence lines." },
        { id: "22_reverse_number.pl",        unit: "Perl Programs", title: "22. Reverse a Number",               concept: "Method 1: reverse() | Method 2: while loop", description: "Two approaches: (1) reverse() flips digit string, int() strips leading zeros. (2) While loop extracts digits via modulo and builds the reversed number.", useCase: "Exam problem.", bioNote: "Reversing a DNA read direction." },
        { id: "23_odd_even.pl",              unit: "Perl Programs", title: "23. Odd or Even",                    concept: "Modulo Operator (%)",            description: "If the number modulo 2 equals 0 it is Even, otherwise it is Odd.", useCase: "Exam problem.", bioNote: "Reading frame check: position modulo 3 determines which codon position a nucleotide occupies." },
        { id: "24_dna_sequence_match.pl",    unit: "Perl Programs", title: "24. DNA Sequence Matching",          concept: "Comprehensive Regex (uc)",       description: "Validates DNA input with a character class regex, then checks for start codon ATG and stop codons TAA/TAG/TGA.", useCase: "Exam problem.", bioNote: "Detecting Open Reading Frames bounded by ATG and stop codons." }
    ]
};
